library(tidyverse)
car_data<- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
head(car_data)
lin_mod= lm(mpg~vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD,data = car_data)
summary(lin_mod)
